# Experiment No. 07
#### D098       60009230197         SIAN RODRIGUES

In [92]:
import numpy as np
import statistics as st

**Question No.1   \
Create a 3x3 matrix of random integers between 1 and 10 and find the total sum of its elements**

In [20]:
mat=np.array([np.random.randint(10) for x in range(9)]).reshape(3,3)
print(mat)
print(sum(sum(mat)))

[[8 6 6]
 [6 5 8]
 [2 8 2]]
51


**Question No.2      \
Generate a 4x4 matrix of random numbers and compute the average of all its elements.**

In [25]:
mat1=np.array([np.random.rand() for x in range(16)]).reshape(4,4)
print(mat1)
print(sum(sum(mat1)) / 16)

[[0.70343968 0.79812085 0.66358047 0.39363167]
 [0.51515822 0.59126451 0.70014982 0.10283327]
 [0.51640206 0.18826844 0.12102971 0.13852329]
 [0.50493613 0.77354856 0.19354201 0.6544277 ]]
0.47242852488333353


**Question No.3     \
Create a 2x3 matrix and find the sum of all elements in the second row.**

In [33]:
mat2=np.array([np.random.rand() for x in range(6)]).reshape(2,3)
print(mat2)
print(sum(mat2[1]))

[[0.15622473 0.85973533 0.52451392]
 [0.04003866 0.36045508 0.34531346]]
0.7458071898248083


**Question No.4     \
Generate a 5x5 matrix of random integers and determine the highest value in each column.** 

In [45]:
mat3=np.array([np.random.randint(25) for x in range(25)]).reshape(5,5)
print(mat3)
# Highest Values in the each columns 

for i in  range(5):
    print(f"Maximum value in the column {i+1} is :{max(mat3[:,i])}")

[[24 24 20  6 12]
 [14 15 21  2  9]
 [ 1 10 21 17 20]
 [20 16  1 15  8]
 [ 4 16 10 15 21]]
Maximum value in the column 1 is :24
Maximum value in the column 2 is :24
Maximum value in the column 3 is :21
Maximum value in the column 4 is :17
Maximum value in the column 5 is :21


**Question No.5 \
Create a 4x4 matrix and calculate the sum of its main diagonal elements.**

In [59]:
mat4=np.array([np.random.randint(16) for x in range(16)]).reshape(4,4)
print(mat4)
sum=0
for i in range(4):
   sum+=mat4[i][i]
print(f"Sum of all elements in the principal diagonals is {sum}")


[[12  1 14  6]
 [ 0 13  9 12]
 [ 9 11 10  7]
 [12  2 11  6]]
Sum of all elements in the principal diagonals is 41


**Question No.6     \
Generate a 3x3 matrix and find the smallest value among all its elements.**

In [72]:
mat5=np.array([np.random.randint(16) for x in range(9)]).reshape(3,3)
print(mat5)
col_min_list=[min(mat5[:,j]) for j in range(3)]
print(f"The minimum values in the whole matrix is : {min(col_min_list)}")


[[13 14 15]
 [ 7  0  6]
 [ 0  4  7]]
The minimum values in the whole matrix is : 0


**Question No.7 \
Create a 4x4 matrix of random integers between 1 and 20 and compute the sum of all elements that are greater than 10.**

In [77]:
mat6=np.array([np.random.randint(1,20) for x in range(16)]).reshape(4,4)
print(mat6)
sum=0
for i in range(4):
    for j in range(4):
        if(mat6[i][j]>10):
            sum+=mat6[i][j]

print(f"The sum of all elements greater than 10 are {sum}")

[[ 1  9  5 15]
 [17  8 16  6]
 [17 16  7  9]
 [12  1 12  5]]
The sum of all elements greater than 10 are 105


**Question No.8     \
Generate a 5x5 matrix of random numbers and find the mean of the maximum values of each row.**

In [94]:
mat7=np.array([np.random.randint(1,20) for x in range(25)]).reshape(5,5)
max_values_row=[max(mat7[:][j]) for j in range(5)]
print(mat7)
val=st.mean(max_values_row)
print("Value of the mean is : ",val)


[[15  4  2  9 11]
 [ 6  5 11  5  8]
 [ 2 19 16 15 10]
 [ 6  4  9 13 11]
 [15 12 15 10  6]]
Value of the mean is :  14


**Question No. 9    \
Create a 3x3 matrix and calculate the difference between the sum of the elements in the first row and the sum of the elements in the last row.**

In [124]:
mat8=np.array([np.random.randint(1,20) for x in range(9)]).reshape(3,3)
print(mat8)
print(f"Sum of Elements in the First and third Row {mat8[0][:]+mat8[2][:]}")

[[15 13 16]
 [19 16  9]
 [19  1  2]]
Sum of Elements in the First and third Row [34 14 18]


**Question No.10    \
Generate a 6x6 matrix of random integers and replace all values below the median with zero.**

In [111]:
mat9=np.array([np.random.randint(1,36) for x in range(36)]).reshape(6,6)
print(mat9)
med=st.median(mat9.flatten())
for i in range(4):
    for j in range(4):
        if(mat9[i][j]<med):
            mat9[i][j]=0
print(f"The median of the given array is : {med}")
print(mat9)


[[32 13 13 30 35 26]
 [ 6 17 20 34  5 31]
 [29  8 32 34 18 15]
 [35  5 33 12 34 14]
 [12 30 33  7  1 22]
 [ 1 35 20  5 12  7]]
The median of the given array is : 19.0
[[32  0  0 30 35 26]
 [ 0  0 20 34  5 31]
 [29  0 32 34 18 15]
 [35  0 33  0 34 14]
 [12 30 33  7  1 22]
 [ 1 35 20  5 12  7]]


**Question No. 11   \
Create a 4x4 matrix and compute the sum of elements in the upper triangular part of the matrix.**

In [114]:
mat10=np.array([np.random.randint(1,36) for x in range(16)]).reshape(4,4)
print(mat10)
sum=0
for i in range(4):
    for j in range(4):
        if(j>=i):
            sum+=mat10[i][j]
print("Sum of all elements in the upper traingular matrix is : ",sum)

[[29 12 32 24]
 [ 4 20 17  8]
 [ 3 28 20 12]
 [34 16 16 17]]
Sum of all elements in the upper traingular matrix is :  191


**Question No. 12   \
Generate a 3x4 matrix of random values and find the standard deviation of the elements in the third column.**

In [122]:
mat11=np.array([np.random.randint(1,36) for x in range(12)]).reshape(3,4)
print(mat11)
std_dev=st.stdev(mat11[:,2].tolist())
print(f"The Standard Deviation in the Third Column is : {std_dev}")

[[14 11 23 12]
 [ 3  4 10 10]
 [16 11 33 18]]
The Standard Deviation in the Third Column is : 11.532562594670797
