# Experiment No.08  DSL 
#### SIAN RODRIGUES         D098
#### 60009230197

In [1]:
import numpy as np
from numpy import median
from scipy import stats as st

In [2]:
# Calculating Mean of an Array 
arr1=np.array([3,6,9,12,15])
print(arr1.mean())

9.0


In [3]:
arr2= np.array([7,3,9,1,5])
print(np.median(arr2))

5.0


In [4]:
arr3=np.array([4,1,2,2,3,4,4])
print(st.mode(arr3)[0])

4


In [5]:
arr4 = np.array([2,4,4,5,5,7,9])
print(f"Variance of the data : {arr4} is {np.var(arr4)}")

Variance of the data : [2 4 4 5 5 7 9] is 4.408163265306123


In [6]:
arr5=np.array([10,12,23,23,16,23,21,16])
print(f"Standard Deviation of the Data : {arr5} is {(np.var(arr5))**0.5}")

Standard Deviation of the Data : [10 12 23 23 16 23 21 16] is 4.898979485566356


In [7]:
arr6=np.array([3,7,8,5,12,14,21,13,18])
print(np.max(arr6)-np.min(arr6))

18


In [8]:
sam_arr1=np.array([1,2,3,4,5])
sam_arr2=np.array([2,4,6,8,10])

# Calculating Carl Pearson's Coefficient
print(type(np.corrcoef(sam_arr1,sam_arr2)))
print(np.corrcoef(sam_arr1,sam_arr2).shape)
print(f"The Corrlation Coeff of {sam_arr1} and {sam_arr2} is {np.corrcoef(sam_arr1,sam_arr2)[0,1]} ")


<class 'numpy.ndarray'>
(2, 2)
The Corrlation Coeff of [1 2 3 4 5] and [ 2  4  6  8 10] is 0.9999999999999999 


In [9]:
print(np.zeros(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
# Generating a 4*4 Identity Matrix 
order = int(input("Enter the order of the Identity Matrix : "))
print(np.eye(order))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
dot1=[1,2,3]
dot2=[4,5,6]
print(f"The dot product of two Arrays {dot1} and {dot2} is : {np.dot(dot1,dot2)}")

The dot product of two Arrays [1, 2, 3] and [4, 5, 6] is : 32


In [12]:
arr_11=np.arange(12)
print(arr_11)
print(arr_11.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
x = np.array([1,2,3,5])
y=np.array([2,3,4,6])
# Length of the Array 
N=len(x)
cumsum=0
for i in range(N):
    cumsum+=(x[i]-np.mean(x))*(y[i]-np.mean(y))
denominator = N*(np.var(x)**0.5)*(np.var(y)**0.5)
corr_r=cumsum/denominator
print(corr_r)

1.0
