# Arithmetic Operations

In [2]:
import numpy as np 

Various types of arithemtic operations can be performed on *Similar sized Array* or *By Broadcasting on Dissimilar Types*

In [5]:
arr1 = np.array([[1,2,3],
				 [4,5,6]])
arr2 = np.array([[9,8,7],
				 [1,2,3]])

**Addition of Two Arrays**

In [8]:
arr_add=arr1+arr2
print(arr_add)
# Element Wise Addition is being performed here 
arr_sub=arr1-arr2
print(arr_sub)

[[10 10 10]
 [ 5  7  9]]
[[-8 -6 -4]
 [ 3  3  3]]


**Scalar Multiplication and Not Matrix Multiplication**

In [11]:
# Note that multiplying two matrices elements --> executes it element wise unlike Mathematical 
# Multiplication
print(arr1*arr1)

# Similarly Dividing it by a Matrix 
print(arr1/arr1) # Division takes Element wise 

print(arr1**2)

[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1  4  9]
 [16 25 36]]


## Using Comparison Operators on Arrays 

Such operations Returns Array of booleans while executing the desired Operation element wise 

In [15]:
arr_big=arr1>arr2
# Note that arr_big is an nd array
print(type(arr_big))
print(arr_big.dtype)
print(arr_big)

# Similarly all types of Comparisons operators can be performed using the Logical Operators 
print(arr1!=arr2)

print(arr1<arr2)

# print()

<class 'numpy.ndarray'>
bool
[[False False False]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [False False False]]


**Operations between Different Sized Arrays is called as Broadcasting Continued in Numpy advanced ..**

## Basic Indexing and Slicing in case of Multi-Dimensional Arrays 