# Introduction to Computational Analysis using Numpy 
1. **Although Numpy is purely Array Oreinted Data Manipulation it is important before Learning pandas which mostly supports Tabular Data Manipulation**
2. **Apart from Arrays , Numerical Python Supports Vaious other Computaional tools like fourier Tranform ,etc**

In [2]:
# Generally Numpy is Imported using alias as py
import numpy as np


**ndarrays are used to store Homogenous Data points**

In [3]:
# Generating Some Random Data Using the random fucntion in Numpy of given shape 
# For the Functin rand() we have to specify the shape 
arr1= np.random.rand(3,3)
print(arr1)
print(type(arr1))  # It is of the type ndarray	 

[[0.29029516 0.20529538 0.83984663]
 [0.64332186 0.36202151 0.27872426]
 [0.50598729 0.17360446 0.55865596]]
<class 'numpy.ndarray'>


In [4]:
# Simple Arithmetic Operatins can be Directly Performed like :-
arr1+10
# 10 gets numerically added to all the data points in the array

array([[10.29029516, 10.20529538, 10.83984663],
       [10.64332186, 10.36202151, 10.27872426],
       [10.50598729, 10.17360446, 10.55865596]])

**.shape & .dtype attribute**

In [5]:
# .shape --> Returns the shape of the array  --> Tuple 
#  .dtype --> returns the data types of the array 
print(arr1.shape)
print(arr1.dtype)

(3, 3)
float64


**Generally even if single element in the array is floating point pandas automatically converts everything to floating point as it is meant for numerical computation**

### Comverting from inbuilt Data to ndArrays 

In [6]:
data1 = [6, 7.5, 8, 0, 1]
sample_arr=np.array(data1)
print(sample_arr)
print(sample_arr.shape)
print(sample_arr.dtype)

[6.  7.5 8.  0.  1. ]
(5,)
float64


**ndim attribute returns the dimension of mentioned ndarray**

In [7]:
sample_arr.ndim

1

**Creating arrays using Functions**

In [8]:
# Creating all the arrays of Zeros
arr=np.zeros(10)
print(arr)
# In order to create Multidimensional Arrays we must Pass the tuple with required dimensions
multidim_zero=np.ones((3,3))
print(multidim_zero)

# Note that all the arrays are by-default created in floasting point Format 
print(arr.dtype)

# Creating Empty arrays --> Initializes array of desired size and shape 

# It is important to note that not always does the np.empty returns array of all zeros in some cases 
#  it may return some garbage Value too..
empty_arr=np.empty((3,3))
print(empty_arr)


# arange(upperlimit) --> can be used to print the numbers between 0 to (upperlimit-1)
print(np.arange(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Creating Identity Matrix 
iden_mat=np.identity(3)
print(iden_mat)

# Note that identity matrix is only defined for a square matrix and only the order of the 
# atrix has to be specified in this case

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### DataTypes for nd Arrays

In [16]:
obj1= np.array([1,2,3], dtype=int)
# Explicitly Mentioning the Data types of the Array
print(obj1)



[1 2 3]


### Type Casting an Array

In [23]:
# 	1] Casting int to float 
obj1=obj1.astype(np.float64)
print(obj1)

#  2] Casting float to int 
# Note that in above case all the num post decimal point are removed 

obj2=np.array([1.23,423.435,4.5,43.24])
print(obj2)
obj2=obj2.astype(np.int64)
print(obj2)

#  3] Casting String representing Numbers into Numeric Form 
#  It is important to note that if casting is not possible 'ValueError' is raised
datearr=np.array(['26','10','2024'])
datearr=datearr.astype(np.int64)
print(datearr)


[1. 2. 3.]
[  1.23  423.435   4.5    43.24 ]
[  1 423   4  43]
[  26   10 2024]


### Practising the Numpy Arrays :-

In [41]:
arr_1=np.array([[[1,2,3],[4,5,6],[7,8,9]],#This Single Line represents 2 Dimensional Arrays
			   [[23,32,4],[32,435,5],[42,43,4]]]) 
print(arr_1.ndim)
print(arr_1)
# It is Important to note that while creating an array of 3 Dimensions or N-Dimensions all the squre 
# brackets should be placed properly

3
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 23  32   4]
  [ 32 435   5]
  [ 42  43   4]]]
